collections:
  activities:
    output: true
    permalink: /:collection/:path/
  groups:
    output: true
    permalink: /:collection/:path/
  people:
    output: true
    permalink: /:collection/:path/
