markdown_ext: "md"

# https://github.com/jekyll/jekyll/issues/302
permalink: pretty
defaults:
  -
    scope:
      type: "pages"
    values:
      permalink: /:path/:basename/

collections:
  activities:
    output: true
    permalink: /:collection/:path/
  groups:
    output: true
    permalink: /:collection/:path/
  people:
    output: true
    permalink: /:collection/:path/
